---
apiVersion: v1
kind: Service
metadata:
  namespace: develop
  name: ts-starter-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: restful
  selector:
    component: ts-starter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: develop
  name: ts-starter-deployment
  labels:
    component: ts-starter
spec:
  selector:
    matchLabels:
      component: ts-starter
  replicas: 1
  template:
    metadata:
      labels:
        component: ts-starter
    spec:
      containers:
        - name: ts-starter
          image: ts-starter:latest # 修改为你的容器镜像点
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: restful
          env:
            - name: NODE_ENV
              value: development
            # 按需自己添加环境变量 可参考 .env.example
          livenessProbe:
            httpGet:
              path: "/ping"
              port: restful # 使用命名的端口
            initialDelaySeconds: 5
            failureThreshold: 2 # 连续探测失败2次才算成功
            timeoutSeconds: 3
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: restful
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15 # 探测频率15秒
            successThreshold: 3 # 连续探测成功3次才算成功
        # 如果需要单独的 worker 来处理 startup
        # - name: worker
        #   image: ts-starter:latest
        #   imagePullPolicy: Always
        #   ports:
        #     - containerPort: 8081
        #       name: restful-worker
        #   env:
        #     - name: WORKER_ENABLE
        #       value: "true"
        #     - name: PORT
        #       value: "8081"
        #     # 其他环境变量与上面 pod 的一致
        #     - name: NODE_ENV
        #       value: development
        #   readinessProbe:
        #     httpGet:
        #       path: "/healthz"
        #       port: restful-worker
        #     initialDelaySeconds: 10
        #     timeoutSeconds: 3
        #     periodSeconds: 15
        #     successThreshold: 3

# 也可以拆分为独立的 Deployment 运行
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: develop
  name: ts-starter-worker-deployment
  labels:
    component: ts-starter-worker
spec:
  selector:
    matchLabels:
      component: ts-starter-worker
  replicas: 1
  template:
    metadata:
      labels:
        component: ts-starter-worker
    spec:
      containers:
        - name: worker
          image: ts-starter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: restful
          env:
            - name: WORKER_ENABLE
              value: "true"
            # 其他环境变量与上面 pod 的一致
            - name: NODE_ENV
              value: development
          livenessProbe:
            httpGet:
              path: "/ping"
              port: restful # 使用命名的端口
            initialDelaySeconds: 5
            failureThreshold: 2 # 连续探测失败2次才算成功
            timeoutSeconds: 3
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: restful
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15 # 探测频率15秒
            successThreshold: 3 # 连续探测成功3次才算成功
